//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emp_ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_details
    {
        public Nullable<int> Serial_No { get; set; }
        public int Employee_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public Nullable<System.DateTime> Date_of_Joining { get; set; }
        public string Address { get; set; }
        public string Department { get; set; }
    }
}
